# Site
title: Voyage.sh
subtitle: 主に日々のなかで気になったことや学んだことを綴るページ
description:
keywords:
author: Redpeacock78
language: ja
timezone: Asia/Tokyo

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://redpeacock78.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam justo turpis, tincidunt ac convallis id.'
location: Location
website: Website

# Add social network profile links
social:
  twitter: https://twitter.com/kazuki_199778
  google+: https://plus.google.com/**profile**
  github: https://github.com/redpeacock78

#opengraph
twitter_profile: 
googleplus_profile: 
fb_admins:
fb_app_id:

fancybox:
fitvids:

excerpt_link: Read More

# Miscellaneous
rss: /atom.xml

theme: ghost-casper
